### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by drewfish** [mercadolibre/flexbuffer-node#1]
Hi,

I'd like to use `ioredis` which depends on this `flexbuffer`. However, this is a corporate environment so we need to have a license to be sure that we can legally use the code, and that we understand any conditions of use.

Could you add a license to this npm module?

**Comment by Ajido** [comment]
+1

**Comment by pavanratnakar** [comment]
+1

**Comment by marcosnils** [comment]
I don't work there anymore, maybe @geisbruch or @matiasrege can help you out with this.

**Comment by geisbruch** [comment]
I will add a MIT License Later today

**Comment by geisbruch** [comment]
Solved, MIT License Added to the repo
